---
  - name: Put SELinux in permissive mode, logging actions that would be blocked.
    selinux:
      policy: targeted
      state: permissive

  - name: copy forkstat
    copy:
      dest: /usr/local/sbin
      src:  forkstat
      mode:  755

  - name: Install helper packages
    yum:
      name:
        - epel-release #htop dependency
        - ca-certificates
      state: latest

  - name: Install helper packages
    yum:
      name:
        - vim
        - wget
        - nc        
        - python-pip
        - htop
        - yum-utils #see files in bash package: repoquery --list bash
        - python-psycopg2